memo: Cleanup PIN entry

diff --git a/memo b/memo
--- a/memo
+++ b/memo
@@ -35,6 +35,10 @@ join_by() { local IFS="$1"; shift; echo "$*"; }
 _copy() {
 	echo
 	read -q ans?"Copy to clipboard? "
+	if [ "$ans" = n ]; then
+		_cleanup 1
+		return 0
+	fi
 	_cleanup
 	[ "$ans" = n ] && return 0
 	command -v xc &>/dev/null || return 1
@@ -42,7 +46,6 @@ _copy() {
 }
 
 show() {
-	echo
 	local list="$1"
 	local c=`echo -E "$list" | wc -l`
 	if (( $c > 1 )); then
@@ -56,20 +59,35 @@ show() {
 	fi
 }
 
+# Clean this line and $1 lines above.
 _cleanup() {
 	printf "\r[K"
+
+	local i=${1:-0}
+	while (( "$i" > 0 )); do
+		printf "[A\r[K"
+		i=$(( $i - 1 ))
+	done
 }
 
 _memo_get() {
 	check_memo
 	check gpg
 
+	local list
 	if (( ! $# )); then
 		local list=(`gpg -qd $memo | cut -d' ' -f1`)
 		echo
 		echo ${list[@]}
 	elif (( $# == 1 )); then
-		local list="`gpg -qd $memo | grep -iE ^$1`"
+		# In case it shortcuts in a fail-loop:
+		# gpg-connect-agent reloadagent /bye
+		list="`gpg -qd --pinentry-mode error $memo 2>/dev/null | grep -iE ^$1`"
+		if [ $? != 0 ]; then
+			list="`gpg -qd $memo | grep -iE ^$1`"
+			[ $? != 0 ] && exit 1
+			_cleanup 2
+		fi
 		show "$list"
 	else
 		local q=`join_by \| $*`
