upd powermode-switch

diff --git a/powermode-switch b/powermode-switch
--- a/powermode-switch
+++ b/powermode-switch
@@ -1,28 +1,70 @@
 #!/bin/sh
 
-g=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`
-echo "Current mode: $g"
+TMPDIR=${TMPDIR:-/tmp}
 
-if [[ $g = powersave ]]; then
-  for c in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
-    sudo sh -c "echo performance > $c" || exit 1
-    echo "CPU upscaled"
-  done
-  sudo rfkill unblock 2 || exit 1
+CURR=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`
+echo "Current mode: $CURR"
+
+# CPU
+
+[ $CURR = performance ] && MODE=powersave || MODE=performance
+for c in `ls -d /sys/devices/system/cpu/cpu[0-9]*`; do
+  sudo sh -c "echo $MODE > $c/cpufreq/scaling_governor" || exit 1
+done
+echo "CPU's set to $MODE mode."
+
+# Bluetooth
+
+BT_IDX=`rfkill list | grep -i bluetooth | head -1 | cut -d: -f1`
+if [ $MODE = performance ]; then
+  sudo rfkill unblock $BT_IDX || exit 1
   echo "Bluetooth enabled"
+elif bluetoothctl info | grep -q "Connected: yes"; then
+  echo
+  echo "Unable to disable bluetooth, following devices connected:"
+  bluetoothctl info | grep "Name:" | cut -d\  -f2-
 else
-  for c in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
-    sudo sh -c "echo powersave > $c" || exit 1
-    echo "CPU downscaled"
-  done
-
-  # Network?
-  if [ -d /sys/bus/pci/devices/0000:09:00.0 ]; then
-    sudo sh -c "echo 1 > /sys/bus/pci/devices/0000:09:00.0/remove" || exit 1
-  fi
-
-  sudo rfkill block 2 || exit 1
+  sudo rfkill block $BT_IDX || exit 1
   echo "Bluetooth disabled"
+fi
 
-  sudo powertop --auto-tune || exit 1
+# PCI devices
+
+_join() {
+  local IFS="$1"
+  shift
+  echo "$*"
+}
+
+if [ $MODE = powersave ]; then
+  PCI_DVCS=()
+  # Nvidia VGA
+  PCI_DVCS+=(10de:1c8c)
+  # Nvidia audio
+  PCI_DVCS+=(10de:0fb9)
+  # ThinkPad ethernet
+  PCI_DVCS+=(8086:15bb)
+  # TODO 0000:09:00.0 Samsung netbook ethernet
+
+  IFS=$'\r\n' PCI_DVCS=($(lspci -nn | sed -En "s/([^ ]+) [^:]+: (.+) \[(`_join \| ${PCI_DVCS[@]}`)\].*/\1 \2/p"))
+
+  echo
+  for d in "${PCI_DVCS[@]}"; do
+    IFS=\  d=(echo $d)
+    DEV=(/sys/bus/pci/devices/*${d[1]})
+    NAME=${d[@]:2}
+    sudo sh -c "echo 1 > $DEV/remove" || exit 1
+    echo "PCI device removed: $NAME"
+  done
+else
+  sudo sh -c "echo 1 > /sys/bus/pci/rescan" || exit 1
+  echo "PCI devices rescanned."
+fi
+
+# Powertop
+
+if [[ ! -f $TMPDIR/.powertop-tuned ]]; then
+  echo
+  sudo powertop --auto-tune \
+  && touch $TMPDIR/.powertop-tuned
 fi
